name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:        # lets you run it manually too
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Stats Card
        uses: anmol098/waka-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Krishna-0510
